{% set org = "GoogleContainerTools" %}
{% set name = "container-diff" %}
{% set version = "0.16.0" %}

{% set src_dir = ["src/github.com", org, name]|join("/") %}


package:
  name: container-diff
  version: {{ version }}

source:
  - url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 255e08e82ffb9139b78054cd0caf0c20b1e6ab8fc359a9a8558da3912b70aba5
    folder: {{ src_dir }}

  - url: https://storage.googleapis.com/container-diff/v{{ version }}/container-diff-windows-amd64.exe  # [win]
    sha256: 2dba72fcb90ef30081f5b1efc4a3495fe4ce13300bd2300df53fde808ec43c45  # [win]
    folder: bin  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler("go") }}  # [unix]

test:
  commands:
    - container-diff

about:
  home: https://github.com/GoogleContainerTools/container-diff
  license: Apache 2.0
  license_family: Apache
  license_file: {{ src_dir }}/LICENSE
  summary: Diff your Docker containers

extra:
  recipe-maintainers:
    - jakirkham
