{% set org = "GoogleContainerTools" %}
{% set name = "container-diff" %}
{% set version = "0.17.0" %}

{% set src_dir = ["src/github.com", org, name]|join("/") %}


package:
  name: container-diff
  version: {{ version }}

source:
  - url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: b1d909c4eff0e3355ba45516daddef0adfa4cdcd0c8b41863060c66f524353f9
    folder: {{ src_dir }}

  - url: https://storage.googleapis.com/container-diff/v{{ version }}/container-diff-windows-amd64.exe  # [win]
    sha256: 2030b9eea8a3bd6a3ac37dbd26011e2b6c10d246caa192954d49e632c446e0ff  # [win]
    folder: bin  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler("go") }}  # [unix]

test:
  commands:
    - container-diff

about:
  home: https://github.com/GoogleContainerTools/container-diff
  license: Apache 2.0
  license_family: Apache
  license_file: {{ src_dir }}/LICENSE
  summary: Diff your Docker containers

extra:
  recipe-maintainers:
    - jakirkham
