{% set org = "GoogleCloudPlatform" %}
{% set name = "container-diff" %}
{% set version = "0.14.0" %}

{% set src_dir = ["go/src/github.com", org, name]|join("/") %}


package:
  name: container-diff
  version: "{{ version }}"

source:
  - url: "https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz"
    sha256: 5dbafdc38524dad60286da2d7a7d303285de2e08e070ce3dcc1488dbfecd116b
    folder: "{{ src_dir }}"

  - url: "https://storage.googleapis.com/container-diff/v{{ version }}/container-diff-windows-amd64.exe"  # [win]
    sha256: a7040bd3f3db6e19cfd7730fde6524feb5bcc5c5f0d81cbeb76f156c4dbd804f                              # [win]
    folder: "bin"                                                                                         # [win]

build:
  number: 0

requirements:
  build:
    - go  # [unix]

test:
  commands:
    - container-diff

about:
  home: https://github.com/GoogleContainerTools/container-diff
  license: Apache 2.0
  license_file: "{{ src_dir }}/LICENSE"
  summary: Diff your Docker containers

extra:
  recipe-maintainers:
    - jakirkham
