travis:
  secure:
    BINSTAR_TOKEN: oyo8T/SN7vSh2gXmJiCdEaXbIrWMHvxaJoGNwkKYCasyqCwu+kV42lQJmCeO5p4x5v9wM3TkQ9ObcFZo94fs/lRWc0fq5MUiHiUzdzaV4vvWjEqly0ZEAJGQxA8vMWx6u3nf2hdP1bOnSd1yzDTCL6bul0BACNbjxhhce5O+JClig+0wEySzfAcc3mSymFSluUnnmh8GYt8H2clPtvcBPNMIO9QjbOpg0Tq7tz/stthiG2+cYrl7VYD/C9HPHD/l8HS1cYf9TC51IZJik32jT4lGznVVzkvAWBKigXtHd4oltIsvxKgf7FCwigguPgtltWR2FnJD125TqVw7WE1obCHBECOkHsd0pqo+0oeufodfPShYQiZU5/uQm9drgv+5dqrwDJ8i/L9yPnF+tAmSrlNHEOLCZf8euxnY0FiYAYyxJ/YvLJlHTXjrpwpdY6bG34oTe2ghvrASCvUpxAS06C5KPLuZQd1Mjpc+Idz61sLo2FC45fgdzw/QQ5lGxjOgkqZmlI5OvEtg/FLDZlpFU1rP4m6TYzl9IJl/hdN22eSxrbR370Gls7yackE9qAi7FJ9OLsHWKbzmHKW00sD0gj4QItVaiL6tdhaKfuHCSg238PTWcV3RGXPwx5KvU0aCSkhpbq5Yxkl/7uHyKG+K92TA+cpf1R3yvfUBGsAAodQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
